services:
  backend:
    build: ./chat_backend
    container_name: messageMe-backend
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=chat_backend.settings
    volumes:
      - ./chat_backend:/app
      - media_data:/app/media
      - static_data:/app/staticfiles
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:stable-alpine
    container_name: messageme-nginx
    depends_on:
      - backend
    ports:
      - 8999:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - media_data:/app/media
      - static_data:/app/staticfiles

  db:
    image: postgres:17-bullseye
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: kyawsan
      POSTGRES_PASSWORD: kyawsan_pwd
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
volumes:
  pgdata:
  media_data:
  static_data:
