services:
  backend:
    build: ./chat_backend
    container_name: messageMe-backend
    command: daphne -b 0.0.0.0 -p 8000 chat_backend.asgi:application
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=chat_backend.settings
    depends_on:
      - db
      - redis

  db:
    image: postgres:17-bullseye
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: kyawsan
      POSTGRES_PASSWORD: kyawsan_pwd
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
volumes:
  pgdata:
